# Project Information
site_name: icopy.site
site_description: 开源文档中文镜像
site_author: chenjiajia
site_url: https://icopy.site

# Repository
repo_name: 'icopy-site/icopy-site.github.io'
repo_url: 'https://github.com/icopy-site/icopy-site.github.io'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2019'

# Contents
nav:
  - 开源文档中文镜像服务: index.md
  - 编程语言: document/language.md
  - 热门框架: document/framework.md
  - 数据库: document/database.md
  - 构建系统: document/build.md
  - 数据可视化: document/dataVisual.md
  - 机器学习: document/ML.md
  - 其他热门项目: document/other.md
  - 开源项目导航:
    - 索引说明: awesome/readme.md
    - 中文导航: https://asmcn.icopy.site/
    - 英文导航: https://asmen.icopy.site/
  - 镜像网站名单: document/whitelist.md
  - 印记中文: https://docschina.org/


# Theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  static_templates:
    - 404.html
  language: 'zh'
  favicon: '_static/img/favicon.ico'
  palette:
    primary: 'white'
    accent: 'blue'
  logo:
    icon: 'g_translate'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  feature:
    tabs: false
# Customization
extra:
  search:
    language: 'en,jp'

extra_javascript:
  - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
  - '_static/js/extra.js'
  - 'https://cdn.staticfile.org/jquery/3.3.1/jquery.min.js'
  - 'https://cdn.staticfile.org/github-repo-widget/e23d85ab8f/jquery.githubRepoWidget.min.js'
  - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
